-- Insert initial super user
-- Note: The password will be encoded by the application's password encoder
-- This is a placeholder that should be updated by the application on first run

-- For manual insertion, you would need to:
-- 1. Use the application's API endpoint: POST /super-admin/initial-super-user
-- 2. Or run the application and use the password encoder to generate the hash

-- Manual INSERT statement (password hash needs to be generated by the application):
-- The password "Password@123" needs to be encoded using the SimplePasswordEncoder

-- Example of what the INSERT would look like (with a placeholder for the encoded password):
/*
INSERT INTO users (
    id,
    company_id,
    email,
    password_hash,
    first_name,
    last_name,
    phone,
    role,
    active,
    email_verified,
    last_login_at,
    created_at,
    updated_at
) VALUES (
    uuid_generate_v4(),
    NULL,  -- Super users don't belong to any company
    'superuser@projectmaster.com',
    'ENCODED_PASSWORD_HASH_HERE',  -- This needs to be generated by the application
    'Super',
    'User',
    '+1234567890',
    'SUPER_USER',
    true,
    false,
    NULL,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
*/

-- The recommended approach is to use the API endpoint after the application starts:
-- POST /super-admin/initial-super-user with the following JSON:
-- {
--   "email": "superuser@projectmaster.com",
--   "password": "Password@123",
--   "firstName": "Super",
--   "lastName": "User",
--   "phone": "+1234567890",
--   "role": "SUPER_USER"
-- }